/**
 * Bundled keyhack validation templates — fully browser-based.
 * No API call required. Update this file to add new providers.
 */
window.BUNDLED_KEYHACK_TEMPLATES = [
  // ── Cloud ──────────────────────────────────────────────────────────────────
  { Keyname: 'AWS Access Key ID', CommandTemplate: 'curl -s -H "Authorization: AWS4-HMAC-SHA256 Credential={{KEY}}" https://sts.amazonaws.com/?Action=GetCallerIdentity&Version=2011-06-15', Method: 'GET', URL: 'https://sts.amazonaws.com/', Header: 'Authorization: AWS4-HMAC-SHA256', Body: '', Description: 'AWS IAM access key — use STS GetCallerIdentity to check identity and permissions.', Notes: 'Requires calculated signature for full validation. Presence alone is a critical leak.' },
  { Keyname: 'AWS Secret Access Key', CommandTemplate: 'aws sts get-caller-identity --access-key-id AKIA... --secret-access-key {{KEY}}', Method: 'GET', URL: '', Header: '', Body: '', Description: 'AWS secret key (40 chars). Combined with an Access Key ID it grants full account access.', Notes: 'Never expose in client code. Rotate immediately on leak.' },
  { Keyname: 'Google (GCP) API Key', CommandTemplate: 'curl -s "https://maps.googleapis.com/maps/api/geocode/json?address=test&key={{KEY}}"', Method: 'GET', URL: 'https://maps.googleapis.com/maps/api/geocode/json', Header: '', Body: '', Description: 'Google Cloud API key — often unrestricted and usable across many services (Maps, Translate, etc).', Notes: 'Check restrictions via the Key restrict on Google Cloud Console.' },
  { Keyname: 'Google OAuth Access Token', CommandTemplate: 'curl -s "https://www.googleapis.com/oauth2/v1/tokeninfo?access_token={{KEY}}"', Method: 'GET', URL: 'https://www.googleapis.com/oauth2/v1/tokeninfo', Header: '', Body: '', Description: 'Google OAuth2 access token — reveals scopes and expiry when introspected.', Notes: '' },
  { Keyname: 'Azure Tenant ID + Client Secret', CommandTemplate: 'curl -s -X POST "https://login.microsoftonline.com/{{KEY}}/oauth2/v2.0/token" -d "grant_type=client_credentials&client_id=APP_ID&client_secret=SECRET&scope=https://graph.microsoft.com/.default"', Method: 'POST', URL: 'https://login.microsoftonline.com/', Header: 'Content-Type: application/x-www-form-urlencoded', Body: 'grant_type=client_credentials', Description: 'Azure AD service principal credentials — can access Graph API, storage, VMs.', Notes: '' },
  { Keyname: 'DigitalOcean API Token', CommandTemplate: 'curl -s -H "Authorization: Bearer {{KEY}}" https://api.digitalocean.com/v2/account', Method: 'GET', URL: 'https://api.digitalocean.com/v2/account', Header: 'Authorization: Bearer', Body: '', Description: 'DigitalOcean personal access token or OAuth token.', Notes: '' },
  { Keyname: 'Heroku API Key', CommandTemplate: 'curl -s -H "Authorization: Bearer {{KEY}}" https://api.heroku.com/account', Method: 'GET', URL: 'https://api.heroku.com/account', Header: 'Authorization: Bearer', Body: '', Description: 'Heroku platform API key — full account access.', Notes: '' },
  { Keyname: 'Cloudflare API Token', CommandTemplate: 'curl -s -H "Authorization: Bearer {{KEY}}" https://api.cloudflare.com/client/v4/user/tokens/verify', Method: 'GET', URL: 'https://api.cloudflare.com/client/v4/user/tokens/verify', Header: 'Authorization: Bearer', Body: '', Description: 'Cloudflare API token — verify status and permissions.', Notes: '' },

  // ── Version Control ─────────────────────────────────────────────────────────
  { Keyname: 'GitHub Personal Access Token', CommandTemplate: 'curl -s -H "Authorization: token {{KEY}}" https://api.github.com/user', Method: 'GET', URL: 'https://api.github.com/user', Header: 'Authorization: token', Body: '', Description: 'GitHub PAT — grants access to private repos, gists, and orgs based on scopes.', Notes: 'Check scopes via X-OAuth-Scopes response header.' },
  { Keyname: 'GitHub OAuth Access Token', CommandTemplate: 'curl -s -H "Authorization: token {{KEY}}" https://api.github.com/user', Method: 'GET', URL: 'https://api.github.com/user', Header: 'Authorization: token', Body: '', Description: 'GitHub OAuth token — same risk profile as PAT.', Notes: '' },
  { Keyname: 'GitLab Personal Access Token', CommandTemplate: 'curl -s -H "PRIVATE-TOKEN: {{KEY}}" https://gitlab.com/api/v4/user', Method: 'GET', URL: 'https://gitlab.com/api/v4/user', Header: 'PRIVATE-TOKEN', Body: '', Description: 'GitLab PAT — access projects, CI/CD pipelines, containers.', Notes: '' },
  { Keyname: 'Bitbucket App Password', CommandTemplate: 'curl -s -u "USERNAME:{{KEY}}" https://api.bitbucket.org/2.0/user', Method: 'GET', URL: 'https://api.bitbucket.org/2.0/user', Header: 'Basic Auth', Body: '', Description: 'Bitbucket app password — used with username for repo access.', Notes: '' },

  // ── Communication / Chat ────────────────────────────────────────────────────
  { Keyname: 'Slack Webhook URL', CommandTemplate: 'curl -s -X POST -H "Content-type: application/json" --data \'{"text":"keyhacks-test"}\' {{KEY}}', Method: 'POST', URL: 'https://hooks.slack.com/services/', Header: 'Content-type: application/json', Body: '{"text":"test"}', Description: 'Slack incoming webhook — can post messages to channels without auth.', Notes: 'Revoke in Slack app management.' },
  { Keyname: 'Slack Bot Token (xoxb)', CommandTemplate: 'curl -s -H "Authorization: Bearer {{KEY}}" https://slack.com/api/auth.test', Method: 'GET', URL: 'https://slack.com/api/auth.test', Header: 'Authorization: Bearer', Body: '', Description: 'Slack bot token — can read/write messages, upload files, access channel history.', Notes: '' },
  { Keyname: 'Slack User Token (xoxp)', CommandTemplate: 'curl -s -H "Authorization: Bearer {{KEY}}" https://slack.com/api/auth.test', Method: 'GET', URL: 'https://slack.com/api/auth.test', Header: 'Authorization: Bearer', Body: '', Description: 'Slack user token — full user-level access to workspace.', Notes: '' },
  { Keyname: 'Discord Bot Token', CommandTemplate: 'curl -s -H "Authorization: Bot {{KEY}}" https://discord.com/api/v10/users/@me', Method: 'GET', URL: 'https://discord.com/api/v10/users/@me', Header: 'Authorization: Bot', Body: '', Description: 'Discord bot token — access guilds, channels, messages.', Notes: '' },
  { Keyname: 'Telegram Bot Token', CommandTemplate: 'curl -s "https://api.telegram.org/bot{{KEY}}/getMe"', Method: 'GET', URL: 'https://api.telegram.org/bot/getMe', Header: '', Body: '', Description: 'Telegram bot token — can send/receive messages, access chats.', Notes: '' },
  { Keyname: 'Twilio Account SID + Auth Token', CommandTemplate: 'curl -s -u "ACCOUNT_SID:{{KEY}}" https://api.twilio.com/2010-04-01/Accounts/ACCOUNT_SID.json', Method: 'GET', URL: 'https://api.twilio.com/2010-04-01/Accounts/', Header: 'Basic Auth', Body: '', Description: 'Twilio credentials — send SMS, make calls, access account data.', Notes: '' },
  { Keyname: 'SendGrid API Key', CommandTemplate: 'curl -s -H "Authorization: Bearer {{KEY}}" https://api.sendgrid.com/v3/user/account', Method: 'GET', URL: 'https://api.sendgrid.com/v3/user/account', Header: 'Authorization: Bearer', Body: '', Description: 'SendGrid API key — send emails, access contacts and stats.', Notes: '' },
  { Keyname: 'Mailgun API Key', CommandTemplate: 'curl -s -u "api:{{KEY}}" https://api.mailgun.net/v3/domains', Method: 'GET', URL: 'https://api.mailgun.net/v3/domains', Header: 'Basic Auth (api:key)', Body: '', Description: 'Mailgun API key — send emails, manage domains and routes.', Notes: '' },
  { Keyname: 'Mailchimp API Key', CommandTemplate: 'curl -s -H "Authorization: apikey {{KEY}}" https://<dc>.api.mailchimp.com/3.0/', Method: 'GET', URL: 'https://<dc>.api.mailchimp.com/3.0/', Header: 'Authorization: apikey', Body: '', Description: 'Mailchimp API key — access audience lists, campaigns, templates.', Notes: 'Datacenter suffix is in the key itself.' },

  // ── Payments ────────────────────────────────────────────────────────────────
  { Keyname: 'Stripe Secret Key', CommandTemplate: 'curl -s -u "{{KEY}}:" https://api.stripe.com/v1/balance', Method: 'GET', URL: 'https://api.stripe.com/v1/balance', Header: 'Authorization: Basic', Body: '', Description: 'Stripe secret key — full access to charges, refunds, customers, and payouts.', Notes: 'Public keys (pk_) are safe; secret keys (sk_) must never leak.' },
  { Keyname: 'Stripe Restricted Key', CommandTemplate: 'curl -s -u "{{KEY}}:" https://api.stripe.com/v1/balance', Method: 'GET', URL: 'https://api.stripe.com/v1/balance', Header: 'Authorization: Basic', Body: '', Description: 'Stripe restricted key (rk_) — limited permissions but still dangerous.', Notes: '' },
  { Keyname: 'PayPal Client Secret', CommandTemplate: 'curl -s -X POST https://api-m.sandbox.paypal.com/v1/oauth2/token -u "CLIENT_ID:{{KEY}}" -d "grant_type=client_credentials"', Method: 'POST', URL: 'https://api-m.paypal.com/v1/oauth2/token', Header: 'Basic Auth', Body: 'grant_type=client_credentials', Description: 'PayPal REST API secret — create payments, issue refunds, access transactions.', Notes: '' },
  { Keyname: 'Square Access Token', CommandTemplate: 'curl -s -H "Authorization: Bearer {{KEY}}" https://connect.squareup.com/v2/locations', Method: 'GET', URL: 'https://connect.squareup.com/v2/locations', Header: 'Authorization: Bearer', Body: '', Description: 'Square access token — manage payments, inventory, customers.', Notes: '' },

  // ── Social / APIs ──────────────────────────────────────────────────────────
  { Keyname: 'Twitter/X Bearer Token', CommandTemplate: 'curl -s -H "Authorization: Bearer {{KEY}}" https://api.twitter.com/2/tweets/search/recent?query=test', Method: 'GET', URL: 'https://api.twitter.com/2/tweets/search/recent', Header: 'Authorization: Bearer', Body: '', Description: 'Twitter/X API v2 bearer token — search tweets, access user data.', Notes: '' },
  { Keyname: 'Facebook Page Access Token', CommandTemplate: 'curl -s "https://graph.facebook.com/me?access_token={{KEY}}"', Method: 'GET', URL: 'https://graph.facebook.com/me', Header: '', Body: '', Description: 'Facebook Graph API page token — manage pages, posts, ads.', Notes: '' },
  { Keyname: 'Instagram Access Token', CommandTemplate: 'curl -s "https://graph.instagram.com/me?fields=id,username&access_token={{KEY}}"', Method: 'GET', URL: 'https://graph.instagram.com/me', Header: '', Body: '', Description: 'Instagram Graph API token — access media, insights, stories.', Notes: '' },

  // ── DevOps / CI/CD ──────────────────────────────────────────────────────────
  { Keyname: 'Docker Hub Personal Access Token', CommandTemplate: 'curl -s -u "USERNAME:{{KEY}}" https://hub.docker.com/v2/user/', Method: 'GET', URL: 'https://hub.docker.com/v2/user/', Header: 'Basic Auth', Body: '', Description: 'Docker Hub PAT — push/pull images, manage orgs.', Notes: '' },
  { Keyname: 'NPM Access Token', CommandTemplate: 'curl -s -H "Authorization: Bearer {{KEY}}" https://registry.npmjs.org/-/whoami', Method: 'GET', URL: 'https://registry.npmjs.org/-/whoami', Header: 'Authorization: Bearer', Body: '', Description: 'NPM token — publish packages, access private packages.', Notes: '' },
  { Keyname: 'PyPI API Token', CommandTemplate: 'curl -s -H "Authorization: Bearer {{KEY}}" https://pypi.org/pypi?%3Aaction=list_packages', Method: 'GET', URL: 'https://pypi.org/', Header: 'Authorization: Bearer', Body: '', Description: 'PyPI token — upload packages, manage releases.', Notes: '' },
  { Keyname: 'Jenkins API Token', CommandTemplate: 'curl -s -u "USERNAME:{{KEY}}" https://jenkins.example.com/me/api/json', Method: 'GET', URL: '', Header: 'Basic Auth', Body: '', Description: 'Jenkins API token — trigger builds, access artifacts, read configs.', Notes: '' },
  { Keyname: 'Terraform Cloud API Token', CommandTemplate: 'curl -s -H "Authorization: Bearer {{KEY}}" https://app.terraform.io/api/v2/account/details', Method: 'GET', URL: 'https://app.terraform.io/api/v2/account/details', Header: 'Authorization: Bearer', Body: '', Description: 'Terraform Cloud token — manage workspaces, states, variables.', Notes: '' },
  { Keyname: 'Vercel Token', CommandTemplate: 'curl -s -H "Authorization: Bearer {{KEY}}" https://api.vercel.com/v2/user', Method: 'GET', URL: 'https://api.vercel.com/v2/user', Header: 'Authorization: Bearer', Body: '', Description: 'Vercel API token — deploy apps, manage domains and env vars.', Notes: '' },
  { Keyname: 'Netlify Personal Access Token', CommandTemplate: 'curl -s -H "Authorization: Bearer {{KEY}}" https://api.netlify.com/api/v1/user', Method: 'GET', URL: 'https://api.netlify.com/api/v1/user', Header: 'Authorization: Bearer', Body: '', Description: 'Netlify PAT — deploy sites, manage forms and functions.', Notes: '' },
  { Keyname: 'CircleCI Personal API Token', CommandTemplate: 'curl -s -H "Circle-Token: {{KEY}}" https://circleci.com/api/v2/me', Method: 'GET', URL: 'https://circleci.com/api/v2/me', Header: 'Circle-Token', Body: '', Description: 'CircleCI token — trigger pipelines, access artifacts.', Notes: '' },

  // ── Database / Storage ──────────────────────────────────────────────────────
  { Keyname: 'MongoDB Connection String', CommandTemplate: 'mongo "{{KEY}}" --eval "db.stats()"', Method: 'GET', URL: '', Header: '', Body: '', Description: 'MongoDB connection URI (mongodb:// or mongodb+srv://) — full database access.', Notes: 'Often contains credentials in URL format.' },
  { Keyname: 'PostgreSQL Connection String', CommandTemplate: 'psql "{{KEY}}" -c "SELECT version();"', Method: 'GET', URL: '', Header: '', Body: '', Description: 'PostgreSQL connection URI (postgresql://) — full database read/write.', Notes: '' },
  { Keyname: 'Redis URL', CommandTemplate: 'redis-cli -u "{{KEY}}" ping', Method: 'GET', URL: '', Header: '', Body: '', Description: 'Redis connection URL (redis://) — full key-value store access.', Notes: '' },
  { Keyname: 'MySQL Connection String', CommandTemplate: 'mysql "{{KEY}}" -e "SELECT version();"', Method: 'GET', URL: '', Header: '', Body: '', Description: 'MySQL connection URI (mysql://) — full database access.', Notes: '' },
  { Keyname: 'Firebase Database URL', CommandTemplate: 'curl -s "{{KEY}}/.json"', Method: 'GET', URL: 'https://*.firebaseio.com/.json', Header: '', Body: '', Description: 'Firebase Realtime Database URL — open instances expose all data as JSON.', Notes: 'Check open database by appending /.json to the URL.' },

  // ── Analytics / Monitoring ──────────────────────────────────────────────────
  { Keyname: 'Google Analytics Tracking ID', CommandTemplate: 'curl -s "https://www.google-analytics.com/collect?v=1&tid={{KEY}}&cid=555&t=pageview&dp=/test"', Method: 'POST', URL: 'https://www.google-analytics.com/collect', Header: '', Body: '', Description: 'GA tracking ID (UA- or G-) — can send spoofed analytics data.', Notes: 'Write-only; cannot read analytics data.' },
  { Keyname: 'Datadog API Key', CommandTemplate: 'curl -s -H "DD-API-KEY: {{KEY}}" https://api.datadoghq.com/api/v1/validate', Method: 'GET', URL: 'https://api.datadoghq.com/api/v1/validate', Header: 'DD-API-KEY', Body: '', Description: 'Datadog API key — submit metrics, logs, and events.', Notes: '' },
  { Keyname: 'New Relic API Key', CommandTemplate: 'curl -s -H "Api-Key: {{KEY}}" https://api.newrelic.com/v2/users/current.json', Method: 'GET', URL: 'https://api.newrelic.com/v2/users/current.json', Header: 'Api-Key', Body: '', Description: 'New Relic REST API key — access APM data, deploy markers.', Notes: '' },
  { Keyname: 'Sentry Auth Token', CommandTemplate: 'curl -s -H "Authorization: Bearer {{KEY}}" https://sentry.io/api/0/organizations/', Method: 'GET', URL: 'https://sentry.io/api/0/organizations/', Header: 'Authorization: Bearer', Body: '', Description: 'Sentry API token — access error tracking data, projects, releases.', Notes: '' },

  // ── Security / Auth ─────────────────────────────────────────────────────────
  { Keyname: 'JWT (JSON Web Token)', CommandTemplate: 'echo "{{KEY}}" | cut -d. -f2 | base64 -d 2>/dev/null | python3 -m json.tool', Method: 'GET', URL: '', Header: '', Body: '', Description: 'JWT token — decode to reveal claims (user ID, roles, expiry). Check for weak algorithms (none, HS256 with known secret).', Notes: 'Use jwt.io for interactive decoding. Check alg=none bypass.' },
  { Keyname: 'Private Key (RSA/EC/DSA)', CommandTemplate: 'ssh -i <(echo "{{KEY}}") user@host', Method: 'GET', URL: '', Header: '', Body: '', Description: 'PEM-encoded private key — can authenticate SSH, sign certificates, decrypt traffic.', Notes: 'Critical if leaked. Rotate immediately.' },
  { Keyname: 'SSH Private Key', CommandTemplate: 'ssh -i <(echo "{{KEY}}") user@host', Method: 'GET', URL: '', Header: '', Body: '', Description: 'SSH private key (OpenSSH format) — direct server access.', Notes: '' },
  { Keyname: 'PGP Private Key Block', CommandTemplate: 'gpg --import <(echo "{{KEY}}")', Method: 'GET', URL: '', Header: '', Body: '', Description: 'PGP private key — can decrypt emails, sign messages.', Notes: '' },
  { Keyname: 'Bearer Token (Generic)', CommandTemplate: 'curl -s -H "Authorization: Bearer {{KEY}}" https://api.example.com/me', Method: 'GET', URL: '', Header: 'Authorization: Bearer', Body: '', Description: 'Generic bearer token — inspect target API /me or /userinfo endpoint.', Notes: 'Replace URL with the target API endpoint.' },

  // ── Misc / Other APIs ───────────────────────────────────────────────────────
  { Keyname: 'OpenAI API Key', CommandTemplate: 'curl -s -H "Authorization: Bearer {{KEY}}" https://api.openai.com/v1/models', Method: 'GET', URL: 'https://api.openai.com/v1/models', Header: 'Authorization: Bearer', Body: '', Description: 'OpenAI API key — access GPT models, generate completions, use DALL-E.', Notes: '' },
  { Keyname: 'Anthropic API Key', CommandTemplate: 'curl -s -H "x-api-key: {{KEY}}" https://api.anthropic.com/v1/messages -H "anthropic-version: 2023-06-01"', Method: 'POST', URL: 'https://api.anthropic.com/v1/messages', Header: 'x-api-key', Body: '', Description: 'Anthropic (Claude) API key — access Claude models.', Notes: '' },
  { Keyname: 'Hugging Face API Token', CommandTemplate: 'curl -s -H "Authorization: Bearer {{KEY}}" https://huggingface.co/api/whoami-v2', Method: 'GET', URL: 'https://huggingface.co/api/whoami-v2', Header: 'Authorization: Bearer', Body: '', Description: 'HuggingFace token — access private models, datasets, spaces.', Notes: '' },
  { Keyname: 'Shopify Access Token', CommandTemplate: 'curl -s -H "X-Shopify-Access-Token: {{KEY}}" https://SHOP.myshopify.com/admin/api/2024-01/shop.json', Method: 'GET', URL: 'https://SHOP.myshopify.com/admin/api/2024-01/shop.json', Header: 'X-Shopify-Access-Token', Body: '', Description: 'Shopify access token — manage products, orders, customers.', Notes: '' },
  { Keyname: 'Airtable API Key', CommandTemplate: 'curl -s -H "Authorization: Bearer {{KEY}}" https://api.airtable.com/v0/meta/whoami', Method: 'GET', URL: 'https://api.airtable.com/v0/meta/whoami', Header: 'Authorization: Bearer', Body: '', Description: 'Airtable personal access token — read/write bases and tables.', Notes: '' },
  { Keyname: 'Notion Integration Token', CommandTemplate: 'curl -s -H "Authorization: Bearer {{KEY}}" -H "Notion-Version: 2022-06-28" https://api.notion.com/v1/users/me', Method: 'GET', URL: 'https://api.notion.com/v1/users/me', Header: 'Authorization: Bearer', Body: '', Description: 'Notion integration token — access pages, databases, blocks.', Notes: '' },
  { Keyname: 'Zapier Webhook URL', CommandTemplate: 'curl -s -X POST -H "Content-type: application/json" --data \'{"test":"keyhacks"}\' {{KEY}}', Method: 'POST', URL: 'https://hooks.zapier.com/hooks/catch/', Header: 'Content-type: application/json', Body: '{"test":"keyhacks"}', Description: 'Zapier webhook — can trigger automated workflows.', Notes: '' },
  { Keyname: 'IFTTT Webhook Key', CommandTemplate: 'curl -s -X POST "https://maker.ifttt.com/trigger/event/with/key/{{KEY}}"', Method: 'POST', URL: 'https://maker.ifttt.com/trigger/', Header: '', Body: '', Description: 'IFTTT webhook key — trigger IFTTT applets.', Notes: '' },
];
