package brain

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/h0tak88r/AutoAR/internal/modules/utils"
)

// OpenRouterRequest represents the request body for OpenRouter API (OpenAI compatible)
type OpenRouterRequest struct {
	Model    string    `json:"model"`
	Messages []Message `json:"messages"`
}

type Message struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

// OpenRouterResponse represents the response body from OpenRouter API
type OpenRouterResponse struct {
	Choices []struct {
		Message Message `json:"message"`
	} `json:"choices"`
	Error *struct {
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

// AICommand represents a command generated by the AI
type AICommand struct {
	Command     string `json:"command"`
	Description string `json:"description"`
}

// AICommandList represents the JSON structure for command lists
type AICommandList struct {
	Commands []AICommand `json:"commands"`
}

const (
	DefaultModel        = "google/gemini-2.0-flash-001"
	OpenRouterEndpoint   = "https://openrouter.ai/api/v1/chat/completions"
	GeminiDirectEndpoint = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"
)

// isJSSercetsContent detects if the content looks like a JS secrets scan file
// Format: [type] url_found_on -> secret_value
func isJSSecretsContent(content string) bool {
	lines := strings.Split(content, "\n")
	count := 0
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if len(line) == 0 {
			continue
		}
		// Match pattern: [SomeType] http... -> ...
		if strings.HasPrefix(line, "[") && strings.Contains(line, "] https://") && strings.Contains(line, " -> ") {
			count++
		}
		if count >= 3 {
			return true
		}
	}
	return false
}

// ExecuteAutonomous analyzes results, runs follow-up commands, and identifies vulnerabilities
func ExecuteAutonomous(resultContent string) (string, error) {
	openRouterKey := os.Getenv("OPENROUTER_API_KEY")
	geminiKey := os.Getenv("GEMINI_API_KEY")

	if openRouterKey == "" && geminiKey == "" {
		return "", fmt.Errorf("neither OPENROUTER_API_KEY nor GEMINI_API_KEY is set")
	}

	// Step 1: Build appropriate prompt based on content type
	log.Printf("[BRAIN] Requesting autonomous commands from AI...")

	var commandPrompt string

	if isJSSecretsContent(resultContent) {
		log.Printf("[BRAIN] Detected JS secrets format, using specialized triage prompt")
		commandPrompt = fmt.Sprintf(`You are an expert bug bounty hunter triaging JS secrets findings.

The input is a list of secrets found in JavaScript files. Each line has the format:
  [SecretType] https://url-of-js-file -> secret_value_found

YOUR TASK:
1. Filter out KNOWN FALSE POSITIVES. These types are almost always false positives and should be IGNORED:
   - google_captcha / reCAPTCHA site keys (start with "6L...")
   - Generic Secret entries where the value is an emoji or unicode character like "㊙️" or similar
   - Generic Secret entries where the value looks like obfuscated JS variable names
   - aws_access_key_id where the value contains "ANPA_COUNTRY_CODE_" (this is a partial string, not a real key)
   - GitHub lines where the value contains "github style" (documentation text, not a real key)
   - sentry_key where the value is just "sentry_key:" (no actual key value)
   - Any sendgrid_api_key that appears to come from an AWS WAF challenge.js file — these are typically obfuscated strings, not real keys. Look for patterns like "bc551e6e3b0d.us-east-1.sdk.awswaf.com" in the URL.

2. For REMAINING real candidates, generate curl commands to VALIDATE them. Examples:
   - For a real Sentry DSN: curl to the Sentry API endpoint
   - For a real DigitalOcean Spaces URL: curl -I the URL to check public access
   - For CloudFront or CDN: curl -I the domain
   - For API keys: look up the provider's validation endpoint and test with curl

3. Format your response EXACTLY as a JSON object. Do NOT suggest grep commands. Do NOT try to search local files:
{
  "commands": [
    {"command": "curl -I https://dante-public-files.lon1.cdn.digitaloceanspaces.com", "description": "Check if DigitalOcean Space is publicly accessible"},
    ...
  ]
}

Only return the JSON object. No other text.

Findings:
%s`, resultContent)
	} else {
		commandPrompt = fmt.Sprintf(`You are an expert security researcher.
Analyze these scan results and provide a JSON list of specific, safe, and effective follow-up commands (e.g., nmap scripts, curl tests) to verify or exploit potential vulnerabilities.
Focus on identifying critical bugs. Do NOT suggest grep or local file search commands.

Constraints:
- Only suggest commands that can run without local files (use curl, nmap, etc.)
- Limit to max 6 commands, prioritize highest-impact
- Only return the JSON object. No other text.

Format:
{
  "commands": [
    {"command": "nmap -sV --script=http-title -p 80 target", "description": "Check HTTP title"},
    ...
  ]
}

Scan Results:
%s`, resultContent)
	}

	log.Printf("[BRAIN] Sending prompt to AI (length: %d)...", len(commandPrompt))
	startTime := time.Now()
	cmdResp, err := callAI(commandPrompt, openRouterKey, geminiKey)
	if err != nil {
		return "", fmt.Errorf("failed to get commands from AI: %w", err)
	}
	log.Printf("[BRAIN] Received AI response in %v", time.Since(startTime))

	// Parse commands
	var cmdList AICommandList
	cleanJSON := strings.TrimSpace(cmdResp)
	if strings.HasPrefix(cleanJSON, "```json") {
		cleanJSON = strings.TrimPrefix(cleanJSON, "```json")
		cleanJSON = strings.TrimSuffix(cleanJSON, "```")
	}
	cleanJSON = strings.TrimSpace(cleanJSON)

	if err := json.Unmarshal([]byte(cleanJSON), &cmdList); err != nil {
		log.Printf("[BRAIN] Error parsing JSON: %v. Response was: %s", err, cleanJSON)
		return "", fmt.Errorf("failed to parse AI commands JSON: %w", err)
	}
	log.Printf("[BRAIN] AI suggested %d commands", len(cmdList.Commands))

	if len(cmdList.Commands) == 0 {
		return "AI suggested no follow-up commands.", nil
	}

	// Step 2: Execute commands
	log.Printf("[BRAIN] Executing %d AI-suggested commands...", len(cmdList.Commands))
	var executionResults bytes.Buffer
	runner := utils.NewCommandRunner(2 * time.Minute)

	for i, cmd := range cmdList.Commands {
		log.Printf("[BRAIN] [%d/%d] Executing: %s", i+1, len(cmdList.Commands), cmd.Command)
		executionResults.WriteString(fmt.Sprintf("\n--- Command: %s ---\nDescription: %s\n", cmd.Command, cmd.Description))
		
		// Parse command string into name and args
		parts := strings.Fields(cmd.Command)
		if len(parts) == 0 {
			continue
		}

		cmdStartTime := time.Now()
		output, err := runner.Run(context.Background(), parts[0], parts[1:]...)
		if err != nil {
			log.Printf("[BRAIN] [%d/%d] Command failed after %v: %v", i+1, len(cmdList.Commands), time.Since(cmdStartTime), err)
			executionResults.WriteString(fmt.Sprintf("Error: %v\nOutput: %s\n", err, string(output)))
		} else {
			log.Printf("[BRAIN] [%d/%d] Command completed in %v", i+1, len(cmdList.Commands), time.Since(cmdStartTime))
			executionResults.WriteString(fmt.Sprintf("Output:\n%s\n", string(output)))
		}
	}

	// Step 3: Analyze command outputs for vulnerabilities
	log.Printf("[BRAIN] Analyzing execution outputs for vulnerabilities...")
	analysisPrompt := fmt.Sprintf(`You are an expert security researcher.
I have executed the following follow-up commands.
Analyze the outputs and identify any confirmed vulnerabilities or high-interest findings.
Be CONCISE — use bullet points. Max 15 lines total.
Specifically look for: exposed storage, valid API keys, RCE, SSRF, or clear misconfigs.

Command Outputs:
%s`, executionResults.String())

	log.Printf("[BRAIN] Sending analysis prompt to AI (length: %d)...", len(analysisPrompt))
	analysisStartTime := time.Now()
	finalAnalysis, err := callAI(analysisPrompt, openRouterKey, geminiKey)
	if err != nil {
		return "", fmt.Errorf("failed to analyze execution results: %w", err)
	}
	log.Printf("[BRAIN] Final analysis received in %v", time.Since(analysisStartTime))

	return finalAnalysis, nil
}

// callAI routes to OpenRouter or direct Gemini
func callAI(prompt, orKey, geminiKey string) (string, error) {
	if orKey != "" {
		res, err := callOpenRouter(prompt, orKey)
		if err == nil {
			return res, nil
		}
		log.Printf("[BRAIN] OpenRouter failed, falling back to direct Gemini if available: %v", err)
	}

	if geminiKey != "" {
		return callGeminiDirect(prompt, geminiKey)
	}

	return "", fmt.Errorf("no valid AI key found or all services failed")
}

func callOpenRouter(prompt, apiKey string) (string, error) {
	reqBody := OpenRouterRequest{
		Model: DefaultModel,
		Messages: []Message{
			{
				Role:    "user",
				Content: prompt,
			},
		},
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return "", err
	}

	req, err := http.NewRequest("POST", OpenRouterEndpoint, bytes.NewBuffer(jsonData))
	if err != nil {
		return "", err
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+apiKey)
	req.Header.Set("HTTP-Referer", "https://github.com/h0tak88r/AutoAR")
	req.Header.Set("X-Title", "AutoAR")

	client := utils.CreateCustomHTTPClient(60 * time.Second)
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("OpenRouter API error %d: %s", resp.StatusCode, string(body))
	}

	var orResp OpenRouterResponse
	if err := json.Unmarshal(body, &orResp); err != nil {
		return "", err
	}

	if orResp.Error != nil {
		return "", fmt.Errorf("OpenRouter error: %s", orResp.Error.Message)
	}

	if len(orResp.Choices) > 0 {
		return orResp.Choices[0].Message.Content, nil
	}

	return "", fmt.Errorf("invalid response from OpenRouter")
}

func callGeminiDirect(prompt, apiKey string) (string, error) {
	reqBody := map[string]interface{}{
		"contents": []map[string]interface{}{
			{
				"parts": []map[string]interface{}{
					{"text": prompt},
				},
			},
		},
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return "", err
	}

	url := fmt.Sprintf("%s?key=%s", GeminiDirectEndpoint, apiKey)
	req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonData))
	if err != nil {
		return "", err
	}

	req.Header.Set("Content-Type", "application/json")

	client := utils.CreateCustomHTTPClient(60 * time.Second)
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("Gemini Direct API error %d: %s", resp.StatusCode, string(body))
	}

	var geminiResp struct {
		Candidates []struct {
			Content struct {
				Parts []struct {
					Text string `json:"text"`
				} `json:"parts"`
			} `json:"content"`
		} `json:"candidates"`
	}

	if err := json.Unmarshal(body, &geminiResp); err != nil {
		return "", err
	}

	if len(geminiResp.Candidates) > 0 && len(geminiResp.Candidates[0].Content.Parts) > 0 {
		return geminiResp.Candidates[0].Content.Parts[0].Text, nil
	}

	return "", fmt.Errorf("invalid response from Gemini Direct")
}

// AnalyzeResults takes a result content and analyzes it using AI (Suggestions only)
func AnalyzeResults(resultContent string) (string, error) {
	openRouterKey := os.Getenv("OPENROUTER_API_KEY")
	geminiKey := os.Getenv("GEMINI_API_KEY")

	if openRouterKey == "" && geminiKey == "" {
		return "", fmt.Errorf("neither OPENROUTER_API_KEY nor GEMINI_API_KEY is set")
	}

	prompt := fmt.Sprintf(`Analyze scan results and suggest NEXT STEPS for security researchers.
Scan Results:
%s`, resultContent)

	return callAI(prompt, openRouterKey, geminiKey)
}

// ChatWithAI sends a multi-turn conversation to the AI.
// history is the previous messages (alternating user/assistant), systemPrompt is injected as the
// very first user message to set context.  Returns the AI's reply text.
func ChatWithAI(history []Message, userMessage string, systemPrompt string) (string, error) {
	openRouterKey := os.Getenv("OPENROUTER_API_KEY")
	geminiKey := os.Getenv("GEMINI_API_KEY")

	if openRouterKey == "" && geminiKey == "" {
		return "", fmt.Errorf("neither OPENROUTER_API_KEY nor GEMINI_API_KEY is set")
	}

	// Build full message list: system prompt first, then history, then new user message
	var messages []Message
	if systemPrompt != "" {
		messages = append(messages, Message{Role: "user", Content: systemPrompt})
		messages = append(messages, Message{Role: "assistant", Content: "Understood. I'm ready to help you with AutoAR reconnaissance and security scanning tasks."})
	}
	messages = append(messages, history...)
	messages = append(messages, Message{Role: "user", Content: userMessage})

	if openRouterKey != "" {
		res, err := callOpenRouterMulti(messages, openRouterKey)
		if err == nil {
			return res, nil
		}
		log.Printf("[BRAIN] OpenRouter failed, falling back to direct Gemini if available: %v", err)
	}

	if geminiKey != "" {
		return callGeminiDirectMulti(messages, geminiKey)
	}

	return "", fmt.Errorf("no valid AI key found or all services failed")
}

// callOpenRouterMulti sends a multi-message conversation to OpenRouter
func callOpenRouterMulti(messages []Message, apiKey string) (string, error) {
	reqBody := OpenRouterRequest{
		Model:    DefaultModel,
		Messages: messages,
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return "", err
	}

	req, err := http.NewRequest("POST", OpenRouterEndpoint, bytes.NewBuffer(jsonData))
	if err != nil {
		return "", err
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+apiKey)
	req.Header.Set("HTTP-Referer", "https://github.com/h0tak88r/AutoAR")
	req.Header.Set("X-Title", "AutoAR")

	client := utils.CreateCustomHTTPClient(90 * time.Second)
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("OpenRouter API error %d: %s", resp.StatusCode, string(body))
	}

	var orResp OpenRouterResponse
	if err := json.Unmarshal(body, &orResp); err != nil {
		return "", err
	}

	if orResp.Error != nil {
		return "", fmt.Errorf("OpenRouter error: %s", orResp.Error.Message)
	}

	if len(orResp.Choices) > 0 {
		return orResp.Choices[0].Message.Content, nil
	}

	return "", fmt.Errorf("invalid response from OpenRouter")
}

// callGeminiDirectMulti sends a multi-turn conversation to Gemini Direct
func callGeminiDirectMulti(messages []Message, apiKey string) (string, error) {
	// Gemini uses "contents" with "role": "user" | "model"
	type geminiPart struct {
		Text string `json:"text"`
	}
	type geminiContent struct {
		Role  string       `json:"role"`
		Parts []geminiPart `json:"parts"`
	}

	var contents []geminiContent
	for _, m := range messages {
		role := m.Role
		if role == "assistant" {
			role = "model"
		}
		contents = append(contents, geminiContent{
			Role:  role,
			Parts: []geminiPart{{Text: m.Content}},
		})
	}

	reqBody := map[string]interface{}{
		"contents": contents,
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return "", err
	}

	url := fmt.Sprintf("%s?key=%s", GeminiDirectEndpoint, apiKey)
	req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonData))
	if err != nil {
		return "", err
	}

	req.Header.Set("Content-Type", "application/json")

	client := utils.CreateCustomHTTPClient(90 * time.Second)
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("Gemini Direct API error %d: %s", resp.StatusCode, string(body))
	}

	var geminiResp struct {
		Candidates []struct {
			Content struct {
				Parts []struct {
					Text string `json:"text"`
				} `json:"parts"`
			} `json:"content"`
		} `json:"candidates"`
	}

	if err := json.Unmarshal(body, &geminiResp); err != nil {
		return "", err
	}

	if len(geminiResp.Candidates) > 0 && len(geminiResp.Candidates[0].Content.Parts) > 0 {
		return geminiResp.Candidates[0].Content.Parts[0].Text, nil
	}

	return "", fmt.Errorf("invalid response from Gemini Direct")
}
