package brain

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/h0tak88r/AutoAR/internal/utils"
)

// OpenRouterRequest represents the request body for OpenRouter API (OpenAI compatible)
type OpenRouterRequest struct {
	Model    string    `json:"model"`
	Messages []Message `json:"messages"`
}

type Message struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

// OpenRouterResponse represents the response body from OpenRouter API
type OpenRouterResponse struct {
	Choices []struct {
		Message Message `json:"message"`
	} `json:"choices"`
	Error *struct {
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

// AICommand represents a command generated by the AI
type AICommand struct {
	Command     string `json:"command"`
	Description string `json:"description"`
}

// AICommandList represents the JSON structure for command lists
type AICommandList struct {
	Commands []AICommand `json:"commands"`
}

const (
	DefaultModel         = "z-ai/glm-4.5-air:free"
	OpenRouterEndpoint   = "https://openrouter.ai/api/v1/chat/completions"
	GeminiDirectEndpoint = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"
	ZAIEndpoint          = "https://api.z.ai/api/coding/paas/v4/chat/completions"
	ZAIDefaultModel      = "glm-4.5-air"
	MaxAgentIterations   = 20
)

// ─── Agent Loop types ─────────────────────────────────────────────────────────

// AgentAction is the JSON object the AI must return each turn.
//
//	{"action": "run_command", "command": "autoar ports scan -d example.com", "reason": "get open ports"}
//	{"action": "run_shell",   "command": "nmap -sV ...",                      "reason": "validate port 8080"}
//	{"action": "report",      "content": "## Findings\n...",                  "notify": true}
//	{"action": "done",        "summary": "Finished. Found X issues."}
type AgentAction struct {
	Action  string `json:"action"`            // run_command | run_shell | report | done
	Command string `json:"command,omitempty"` // for run_command / run_shell
	Reason  string `json:"reason,omitempty"`  // why this command
	Content string `json:"content,omitempty"` // for report
	Notify  bool   `json:"notify,omitempty"`  // should it go to Discord?
	Summary string `json:"summary,omitempty"` // for done
}

// AgentResult summarises what the agent did
type AgentResult struct {
	Summary    string   // Final summary from the AI
	Reports    []string // Markdown text blocks the AI decided to report
	ShouldSend bool     // Whether any report had notify:true
}

// autoarSystemPrompt is injected once at conversation start.
const autoarSystemPrompt = `You are AutoAR Agent — an expert autonomous bug-bounty reconnaissance AI.
You control the AutoAR security tool via JSON actions.

## AutoAR CLI Commands (use exactly as shown)
| Command | What it does |
|---------|-------------|
| autoar subdomains get -d DOMAIN | Enumerate subdomains (outputs txt list) |
| autoar livehosts get -d DOMAIN [-t THREADS] | Filter live HTTP hosts (outputs JSON per-host) |
| autoar ports scan -d DOMAIN | Port scan all live hosts (outputs JSON per-host with open ports) |
| autoar nuclei run -d DOMAIN | Run Nuclei vulnerability templates (outputs JSON findings) |
| autoar js scan -d DOMAIN | Extract JS files and scan for secrets (outputs [type] url -> value) |
| autoar urls collect -d DOMAIN | Collect URLs from crawling & wayback (outputs txt URL list) |
| autoar tech detect -d DOMAIN | Detect web technologies per host (outputs JSON) |
| autoar gf scan -d DOMAIN | Pattern-match URLs (outputs txt) |
| autoar reflection scan -d DOMAIN | Scan for reflected parameters (outputs txt) |
| autoar dns takeover -d DOMAIN | DNS subdomain takeover scan (outputs JSON) |
| autoar cnames get -d DOMAIN | Collect CNAME records (outputs txt) |
| autoar ffuf fuzz -d DOMAIN | Directory/path fuzzing across live hosts (outputs txt) |
| autoar misconfig scan TARGET | Check cloud/web misconfigurations (outputs JSON) |
| autoar s3 enum -b ROOT_DOMAIN | Enumerate S3/cloud buckets (outputs JSON) |
| autoar github scan -r OWNER/REPO | Scan GitHub repo for secrets (outputs txt) |
| autoar zerodays scan -d DOMAIN | CVE/zero-day scan on live hosts (outputs JSON) |
| autoar domain run -d DOMAIN | Full deep-recon workflow |
| autoar status --json | Poll active scan progress: {"active_scans":[{"target":"","scan_type":"","status":"","current_phase":0,"total_phases":0,"phase_name":""}]} |
| autoar explain PATH | Feed any result file to AI for triage: returns markdown analysis |

## Rules
1. Each turn respond ONLY with a single valid JSON object matching one of the action types.
2. After running autoar commands, analyze the output carefully.
3. For open ports: validate with nmap scripts (run_shell). For nuclei highs: curl to confirm. For JS secrets: curl to validate.
4. Use "report" + "notify": true ONLY if you found a real, validated, high-confidence finding worth reporting.
5. Use "report" + "notify": false for informational summaries.
6. Use "done" when the request is fully handled.
7. Never invent scan results. Only act on what you actually received.
8. Max iterations: 20. For long scans, use 'autoar status --json' to poll progress between iterations instead of waiting blindly.`

// RunAgentLoop runs the natural language AI agent loop.
// userRequest: the user's NL message (e.g. "scan example.com for open ports")
// progressFn: called with progress strings to post to Discord
// Returns AgentResult with all reports and a final summary.
func RunAgentLoop(userRequest string, progressFn func(string)) (*AgentResult, error) {
	openRouterKey := os.Getenv("OPENROUTER_API_KEY")
	geminiKey := os.Getenv("GEMINI_API_KEY")
	if openRouterKey == "" && geminiKey == "" {
		return nil, fmt.Errorf("neither OPENROUTER_API_KEY nor GEMINI_API_KEY is set")
	}

	result := &AgentResult{}
	history := []Message{}

	// Seed with user request
	firstUserMsg := fmt.Sprintf("User request: %s", userRequest)

	log.Printf("[AGENT] Starting agent loop for: %s", userRequest)

	runner := utils.NewCommandRunner(5 * time.Minute)

	for iter := 0; iter < MaxAgentIterations; iter++ {
		log.Printf("[AGENT] Iteration %d/%d", iter+1, MaxAgentIterations)

		var aiReply string
		var err error

		if iter == 0 {
			aiReply, err = ChatWithAI(history, firstUserMsg, autoarSystemPrompt)
		} else {
			aiReply, err = ChatWithAI(history, "", "")
		}
		if err != nil {
			return nil, fmt.Errorf("AI call failed at iter %d: %w", iter+1, err)
		}

		log.Printf("[AGENT] AI reply (raw): %s", aiReply)

		// Append assistant reply to history
		history = append(history, Message{Role: "assistant", Content: aiReply})

		// Parse action — retry up to 2 times on bad JSON so one hallucination
		// doesn't kill the whole session.
		var action *AgentAction
		for attempt := 0; attempt < 2; attempt++ {
			action, err = parseAgentAction(aiReply)
			if err == nil {
				break
			}
			if attempt == 0 {
				log.Printf("[AGENT] Bad JSON (attempt %d): %v — asking AI to retry", attempt+1, err)
				history = append(history, Message{
					Role:    "user",
					Content: "Your last response was not valid JSON. Please respond with EXACTLY one JSON action object and nothing else. Example: {\"action\":\"run_command\",\"command\":\"autoar subdomains get -d example.com\",\"reason\":\"start recon\"}",
				})
				aiReply, err = ChatWithAI(history, "", "")
				if err != nil {
					log.Printf("[AGENT] AI retry call failed: %v — skipping iteration", err)
					break
				}
				history = append(history, Message{Role: "assistant", Content: aiReply})
			}
		}
		if action == nil {
			log.Printf("[AGENT] Could not parse action after retries — skipping iteration")
			history = append(history, Message{Role: "user", Content: "Skipping this turn due to invalid response. Please continue with a valid JSON action."})
			continue
		}

		switch action.Action {
		case "run_command", "run_shell":
			label := "🔧 AutoAR"
			if action.Action == "run_shell" {
				label = "🔍 Shell"
			}
			msg := fmt.Sprintf("%s: `%s`\n> _%s_", label, action.Command, action.Reason)
			if progressFn != nil {
				progressFn(msg)
			}
			log.Printf("[AGENT] Running: %s", action.Command)

			parts := strings.Fields(action.Command)
			var output []byte
			if len(parts) > 0 {
				output, err = runner.Run(context.Background(), parts[0], parts[1:]...)
			}

			var toolResult string
			if err != nil {
				toolResult = fmt.Sprintf("Command failed: %v\nOutput:\n%s", err, string(output))
				log.Printf("[AGENT] Command error: %v", err)
			} else {
				toolResult = string(output)
				if len(toolResult) == 0 {
					toolResult = "(no output)"
				}
			}

			// Smart truncation: keep head (startup info) + tail (where results live)
			toolResult = smartTruncate(toolResult, 8000)

			feedback := fmt.Sprintf("Command output:\n```\n%s\n```", toolResult)
			history = append(history, Message{Role: "user", Content: feedback})

		case "report":
			result.Reports = append(result.Reports, action.Content)
			if action.Notify {
				result.ShouldSend = true
			}
			if progressFn != nil {
				notifyStr := ""
				if action.Notify {
					notifyStr = " *(will be posted to Discord)*"
				}
				progressFn(fmt.Sprintf("📋 Agent generated a report%s", notifyStr))
			}
			history = append(history, Message{Role: "user", Content: "Report recorded. Continue if needed or use done."})

		case "done":
			result.Summary = action.Summary
			log.Printf("[AGENT] Agent done: %s", action.Summary)
			return result, nil

		default:
			log.Printf("[AGENT] Unknown action: %s — stopping", action.Action)
			return result, nil
		}
	}

	// Hit max iterations
	if result.Summary == "" {
		result.Summary = "Agent reached maximum iterations."
	}
	return result, nil
}

// smartTruncate keeps the beginning (startup/info) and the end (results) of long output.
// This is better than naive head-only truncation because scan results are at the end.
func smartTruncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	headLen := 2000
	tailLen := maxLen - headLen - 50 // 50 chars for the separator line
	if tailLen < 500 {
		// maxLen is very small, just do a simple truncation
		return s[:maxLen] + "...(truncated)"
	}
	head := s[:headLen]
	tail := s[len(s)-tailLen:]
	skipped := len(s) - headLen - tailLen
	return head + fmt.Sprintf("\n\n...[%d bytes omitted]...\n\n", skipped) + tail
}

// parseAgentAction extracts the JSON AgentAction from a possibly-markdown-wrapped AI reply.
func parseAgentAction(reply string) (*AgentAction, error) {
	clean := strings.TrimSpace(reply)
	// Strip code fences if present
	if strings.HasPrefix(clean, "```json") {
		clean = strings.TrimPrefix(clean, "```json")
		clean = strings.TrimSuffix(clean, "```")
	} else if strings.HasPrefix(clean, "```") {
		clean = strings.TrimPrefix(clean, "```")
		clean = strings.TrimSuffix(clean, "```")
	}
	clean = strings.TrimSpace(clean)

	// Find the first { … } block
	start := strings.Index(clean, "{")
	end := strings.LastIndex(clean, "}")
	if start == -1 || end == -1 || end < start {
		return nil, fmt.Errorf("no JSON object found in reply: %q", clean)
	}
	clean = clean[start : end+1]

	var action AgentAction
	if err := json.Unmarshal([]byte(clean), &action); err != nil {
		return nil, fmt.Errorf("JSON unmarshal error: %w (raw: %q)", err, clean)
	}
	if action.Action == "" {
		return nil, fmt.Errorf("action field is empty in JSON: %q", clean)
	}
	return &action, nil
}

// isJSSercetsContent detects if the content looks like a JS secrets scan file
// Format: [type] url_found_on -> secret_value
func isJSSecretsContent(content string) bool {
	lines := strings.Split(content, "\n")
	count := 0
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if len(line) == 0 {
			continue
		}
		// Match pattern: [SomeType] http... -> ...
		if strings.HasPrefix(line, "[") && strings.Contains(line, "] https://") && strings.Contains(line, " -> ") {
			count++
		}
		if count >= 3 {
			return true
		}
	}
	return false
}

// ExecuteAutonomous analyzes results, runs follow-up commands, and identifies vulnerabilities
func ExecuteAutonomous(resultContent string) (string, error) {
	openRouterKey := os.Getenv("OPENROUTER_API_KEY")
	geminiKey := os.Getenv("GEMINI_API_KEY")

	if openRouterKey == "" && geminiKey == "" {
		return "", fmt.Errorf("neither OPENROUTER_API_KEY nor GEMINI_API_KEY is set")
	}

	// Step 1: Build appropriate prompt based on content type
	log.Printf("[BRAIN] Requesting autonomous commands from AI...")

	var commandPrompt string

	if isJSSecretsContent(resultContent) {
		log.Printf("[BRAIN] Detected JS secrets format, using specialized triage prompt")
		commandPrompt = fmt.Sprintf(`You are an expert bug bounty hunter triaging JS secrets findings.

The input is a list of secrets found in JavaScript files. Each line has the format:
  [SecretType] https://url-of-js-file -> secret_value_found

YOUR TASK:
1. Filter out KNOWN FALSE POSITIVES. These types are almost always false positives and should be IGNORED:
   - google_captcha / reCAPTCHA site keys (start with "6L...")
   - Generic Secret entries where the value is an emoji or unicode character like "㊙️" or similar
   - Generic Secret entries where the value looks like obfuscated JS variable names
   - aws_access_key_id where the value contains "ANPA_COUNTRY_CODE_" (this is a partial string, not a real key)
   - GitHub lines where the value contains "github style" (documentation text, not a real key)
   - sentry_key where the value is just "sentry_key:" (no actual key value)
   - Any sendgrid_api_key that appears to come from an AWS WAF challenge.js file — these are typically obfuscated strings, not real keys. Look for patterns like "bc551e6e3b0d.us-east-1.sdk.awswaf.com" in the URL.

2. For REMAINING real candidates, generate curl commands to VALIDATE them. Examples:
   - For a real Sentry DSN: curl to the Sentry API endpoint
   - For a real DigitalOcean Spaces URL: curl -I the URL to check public access
   - For CloudFront or CDN: curl -I the domain
   - For API keys: look up the provider's validation endpoint and test with curl

3. Format your response EXACTLY as a JSON object. Do NOT suggest grep commands. Do NOT try to search local files:
{
  "commands": [
    {"command": "curl -I https://dante-public-files.lon1.cdn.digitaloceanspaces.com", "description": "Check if DigitalOcean Space is publicly accessible"},
    ...
  ]
}

Only return the JSON object. No other text.

Findings:
%s`, resultContent)
	} else {
		commandPrompt = fmt.Sprintf(`You are an expert security researcher.
Analyze these scan results and provide a JSON list of specific, safe, and effective follow-up commands (e.g., nmap scripts, curl tests) to verify or exploit potential vulnerabilities.
Focus on identifying critical bugs. Do NOT suggest grep or local file search commands.

Constraints:
- Only suggest commands that can run without local files (use curl, nmap, etc.)
- Limit to max 6 commands, prioritize highest-impact
- Only return the JSON object. No other text.

Format:
{
  "commands": [
    {"command": "nmap -sV --script=http-title -p 80 target", "description": "Check HTTP title"},
    ...
  ]
}

Scan Results:
%s`, resultContent)
	}

	log.Printf("[BRAIN] Sending prompt to AI (length: %d)...", len(commandPrompt))
	startTime := time.Now()
	cmdResp, err := callAI(commandPrompt, openRouterKey, geminiKey)
	if err != nil {
		return "", fmt.Errorf("failed to get commands from AI: %w", err)
	}
	log.Printf("[BRAIN] Received AI response in %v", time.Since(startTime))

	// Parse commands
	var cmdList AICommandList
	cleanJSON := strings.TrimSpace(cmdResp)
	if strings.HasPrefix(cleanJSON, "```json") {
		cleanJSON = strings.TrimPrefix(cleanJSON, "```json")
		cleanJSON = strings.TrimSuffix(cleanJSON, "```")
	}
	cleanJSON = strings.TrimSpace(cleanJSON)

	if err := json.Unmarshal([]byte(cleanJSON), &cmdList); err != nil {
		log.Printf("[BRAIN] Error parsing JSON: %v. Response was: %s", err, cleanJSON)
		return "", fmt.Errorf("failed to parse AI commands JSON: %w", err)
	}
	log.Printf("[BRAIN] AI suggested %d commands", len(cmdList.Commands))

	if len(cmdList.Commands) == 0 {
		return "AI suggested no follow-up commands.", nil
	}

	// Step 2: Execute commands
	log.Printf("[BRAIN] Executing %d AI-suggested commands...", len(cmdList.Commands))
	var executionResults bytes.Buffer
	runner := utils.NewCommandRunner(2 * time.Minute)

	for i, cmd := range cmdList.Commands {
		log.Printf("[BRAIN] [%d/%d] Executing: %s", i+1, len(cmdList.Commands), cmd.Command)
		executionResults.WriteString(fmt.Sprintf("\n--- Command: %s ---\nDescription: %s\n", cmd.Command, cmd.Description))

		// Parse command string into name and args
		parts := strings.Fields(cmd.Command)
		if len(parts) == 0 {
			continue
		}

		cmdStartTime := time.Now()
		output, err := runner.Run(context.Background(), parts[0], parts[1:]...)
		if err != nil {
			log.Printf("[BRAIN] [%d/%d] Command failed after %v: %v", i+1, len(cmdList.Commands), time.Since(cmdStartTime), err)
			executionResults.WriteString(fmt.Sprintf("Error: %v\nOutput: %s\n", err, string(output)))
		} else {
			log.Printf("[BRAIN] [%d/%d] Command completed in %v", i+1, len(cmdList.Commands), time.Since(cmdStartTime))
			executionResults.WriteString(fmt.Sprintf("Output:\n%s\n", string(output)))
		}
	}

	// Step 3: Analyze command outputs for vulnerabilities
	log.Printf("[BRAIN] Analyzing execution outputs for vulnerabilities...")
	analysisPrompt := fmt.Sprintf(`You are an expert security researcher.
I have executed the following follow-up commands.
Analyze the outputs and identify any confirmed vulnerabilities or high-interest findings.
Be CONCISE — use bullet points. Max 15 lines total.
Specifically look for: exposed storage, valid API keys, RCE, SSRF, or clear misconfigs.

Command Outputs:
%s`, executionResults.String())

	log.Printf("[BRAIN] Sending analysis prompt to AI (length: %d)...", len(analysisPrompt))
	analysisStartTime := time.Now()
	finalAnalysis, err := callAI(analysisPrompt, openRouterKey, geminiKey)
	if err != nil {
		return "", fmt.Errorf("failed to analyze execution results: %w", err)
	}
	log.Printf("[BRAIN] Final analysis received in %v", time.Since(analysisStartTime))

	return finalAnalysis, nil
}

// callAI routes to OpenRouter, Z.ai or direct Gemini
func callAI(prompt, orKey, geminiKey string) (string, error) {
	zaiKey := os.Getenv("ZHIPU_API_KEY")

	if orKey != "" {
		res, err := callOpenRouter(prompt, orKey)
		if err == nil {
			return res, nil
		}
		log.Printf("[BRAIN] OpenRouter failed, falling back to other providers: %v", err)
	}

	if zaiKey != "" {
		res, err := callZAI(prompt, zaiKey)
		if err == nil {
			return res, nil
		}
		log.Printf("[BRAIN] Z.ai failed, falling back to direct Gemini: %v", err)
	}

	if geminiKey != "" {
		return callGeminiDirect(prompt, geminiKey)
	}

	return "", fmt.Errorf("no valid AI key found or all services failed")
}

func callOpenRouter(prompt, apiKey string) (string, error) {
	reqBody := OpenRouterRequest{
		Model: DefaultModel,
		Messages: []Message{
			{
				Role:    "user",
				Content: prompt,
			},
		},
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return "", err
	}

	req, err := http.NewRequest("POST", OpenRouterEndpoint, bytes.NewBuffer(jsonData))
	if err != nil {
		return "", err
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+apiKey)
	req.Header.Set("HTTP-Referer", "https://github.com/h0tak88r/AutoAR")
	req.Header.Set("X-Title", "AutoAR")

	client := utils.CreateCustomHTTPClient(60 * time.Second)
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("OpenRouter API error %d: %s", resp.StatusCode, string(body))
	}

	var orResp OpenRouterResponse
	if err := json.Unmarshal(body, &orResp); err != nil {
		return "", err
	}

	if orResp.Error != nil {
		return "", fmt.Errorf("OpenRouter error: %s", orResp.Error.Message)
	}

	if len(orResp.Choices) > 0 {
		return orResp.Choices[0].Message.Content, nil
	}

	return "", fmt.Errorf("invalid response from OpenRouter")
}

func callGeminiDirect(prompt, apiKey string) (string, error) {
	reqBody := map[string]interface{}{
		"contents": []map[string]interface{}{
			{
				"parts": []map[string]interface{}{
					{"text": prompt},
				},
			},
		},
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return "", err
	}

	url := fmt.Sprintf("%s?key=%s", GeminiDirectEndpoint, apiKey)
	req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonData))
	if err != nil {
		return "", err
	}

	req.Header.Set("Content-Type", "application/json")

	client := utils.CreateCustomHTTPClient(60 * time.Second)
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("Gemini Direct API error %d: %s", resp.StatusCode, string(body))
	}

	var geminiResp struct {
		Candidates []struct {
			Content struct {
				Parts []struct {
					Text string `json:"text"`
				} `json:"parts"`
			} `json:"content"`
		} `json:"candidates"`
	}

	if err := json.Unmarshal(body, &geminiResp); err != nil {
		return "", err
	}

	if len(geminiResp.Candidates) > 0 && len(geminiResp.Candidates[0].Content.Parts) > 0 {
		return geminiResp.Candidates[0].Content.Parts[0].Text, nil
	}

	return "", fmt.Errorf("invalid response from Gemini Direct")
}

// AnalyzeResults takes a result content and analyzes it using AI (Suggestions only)
func AnalyzeResults(resultContent string) (string, error) {
	openRouterKey := os.Getenv("OPENROUTER_API_KEY")
	geminiKey := os.Getenv("GEMINI_API_KEY")

	if openRouterKey == "" && geminiKey == "" {
		return "", fmt.Errorf("neither OPENROUTER_API_KEY nor GEMINI_API_KEY is set")
	}

	prompt := fmt.Sprintf(`Analyze scan results and suggest NEXT STEPS for security researchers.
Scan Results:
%s`, resultContent)

	return callAI(prompt, openRouterKey, geminiKey)
}

// ChatWithAI sends a multi-turn conversation to the AI.
// history is the previous messages (alternating user/assistant), systemPrompt is injected as the
// very first user message to set context.  Returns the AI's reply text.
func ChatWithAI(history []Message, userMessage string, systemPrompt string) (string, error) {
	openRouterKey := os.Getenv("OPENROUTER_API_KEY")
	geminiKey := os.Getenv("GEMINI_API_KEY")

	if openRouterKey == "" && geminiKey == "" {
		return "", fmt.Errorf("neither OPENROUTER_API_KEY nor GEMINI_API_KEY is set")
	}

	// Build full message list: system prompt first, then history, then new user message
	var messages []Message
	if systemPrompt != "" {
		messages = append(messages, Message{Role: "user", Content: systemPrompt})
		messages = append(messages, Message{Role: "assistant", Content: "Understood. I'm ready to help you with AutoAR reconnaissance and security scanning tasks."})
	}
	messages = append(messages, history...)
	messages = append(messages, Message{Role: "user", Content: userMessage})

	if openRouterKey != "" {
		res, err := callOpenRouterMulti(messages, openRouterKey)
		if err == nil {
			return res, nil
		}
		log.Printf("[BRAIN] OpenRouter failed, falling back to other providers: %v", err)
	}

	zaiKey := os.Getenv("ZHIPU_API_KEY")
	if zaiKey != "" {
		res, err := callZAIMulti(messages, zaiKey)
		if err == nil {
			return res, nil
		}
		log.Printf("[BRAIN] Z.ai failed, falling back to Gemini: %v", err)
	}

	if geminiKey != "" {
		return callGeminiDirectMulti(messages, geminiKey)
	}

	return "", fmt.Errorf("no valid AI key found or all services failed")
}

// callOpenRouterMulti sends a multi-message conversation to OpenRouter
func callOpenRouterMulti(messages []Message, apiKey string) (string, error) {
	reqBody := OpenRouterRequest{
		Model:    DefaultModel,
		Messages: messages,
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return "", err
	}

	req, err := http.NewRequest("POST", OpenRouterEndpoint, bytes.NewBuffer(jsonData))
	if err != nil {
		return "", err
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+apiKey)
	req.Header.Set("HTTP-Referer", "https://github.com/h0tak88r/AutoAR")
	req.Header.Set("X-Title", "AutoAR")

	client := utils.CreateCustomHTTPClient(90 * time.Second)
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("OpenRouter API error %d: %s", resp.StatusCode, string(body))
	}

	var orResp OpenRouterResponse
	if err := json.Unmarshal(body, &orResp); err != nil {
		return "", err
	}

	if orResp.Error != nil {
		return "", fmt.Errorf("OpenRouter error: %s", orResp.Error.Message)
	}

	if len(orResp.Choices) > 0 {
		return orResp.Choices[0].Message.Content, nil
	}

	return "", fmt.Errorf("invalid response from OpenRouter")
}

// callGeminiDirectMulti sends a multi-turn conversation to Gemini Direct
func callGeminiDirectMulti(messages []Message, apiKey string) (string, error) {
	// Gemini uses "contents" with "role": "user" | "model"
	type geminiPart struct {
		Text string `json:"text"`
	}
	type geminiContent struct {
		Role  string       `json:"role"`
		Parts []geminiPart `json:"parts"`
	}

	var contents []geminiContent
	for _, m := range messages {
		role := m.Role
		if role == "assistant" {
			role = "model"
		}
		contents = append(contents, geminiContent{
			Role:  role,
			Parts: []geminiPart{{Text: m.Content}},
		})
	}

	reqBody := map[string]interface{}{
		"contents": contents,
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return "", err
	}

	url := fmt.Sprintf("%s?key=%s", GeminiDirectEndpoint, apiKey)
	req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonData))
	if err != nil {
		return "", err
	}

	req.Header.Set("Content-Type", "application/json")

	client := utils.CreateCustomHTTPClient(90 * time.Second)
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("Gemini Direct API error %d: %s", resp.StatusCode, string(body))
	}

	var geminiResp struct {
		Candidates []struct {
			Content struct {
				Parts []struct {
					Text string `json:"text"`
				} `json:"parts"`
			} `json:"content"`
		} `json:"candidates"`
	}

	if err := json.Unmarshal(body, &geminiResp); err != nil {
		return "", err
	}

	if len(geminiResp.Candidates) > 0 && len(geminiResp.Candidates[0].Content.Parts) > 0 {
		return geminiResp.Candidates[0].Content.Parts[0].Text, nil
	}

	return "", fmt.Errorf("invalid response from Gemini Direct")
}

func callZAI(prompt, apiKey string) (string, error) {
	reqBody := OpenRouterRequest{
		Model: ZAIDefaultModel,
		Messages: []Message{
			{
				Role:    "user",
				Content: prompt,
			},
		},
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return "", err
	}

	req, err := http.NewRequest("POST", ZAIEndpoint, bytes.NewBuffer(jsonData))
	if err != nil {
		return "", err
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+apiKey)

	client := utils.CreateCustomHTTPClient(60 * time.Second)
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("Z.ai API error %d: %s", resp.StatusCode, string(body))
	}

	var orResp OpenRouterResponse
	if err := json.Unmarshal(body, &orResp); err != nil {
		return "", err
	}

	if orResp.Error != nil {
		return "", fmt.Errorf("Z.ai error: %s", orResp.Error.Message)
	}

	if len(orResp.Choices) > 0 {
		return orResp.Choices[0].Message.Content, nil
	}

	return "", fmt.Errorf("invalid response from Z.ai")
}

func callZAIMulti(messages []Message, apiKey string) (string, error) {
	reqBody := OpenRouterRequest{
		Model:    ZAIDefaultModel,
		Messages: messages,
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return "", err
	}

	req, err := http.NewRequest("POST", ZAIEndpoint, bytes.NewBuffer(jsonData))
	if err != nil {
		return "", err
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+apiKey)

	client := utils.CreateCustomHTTPClient(90 * time.Second)
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("Z.ai Multi API error %d: %s", resp.StatusCode, string(body))
	}

	var orResp OpenRouterResponse
	if err := json.Unmarshal(body, &orResp); err != nil {
		return "", err
	}

	if orResp.Error != nil {
		return "", fmt.Errorf("Z.ai error: %s", orResp.Error.Message)
	}

	if len(orResp.Choices) > 0 {
		return orResp.Choices[0].Message.Content, nil
	}

	return "", fmt.Errorf("invalid response from Z.ai")
}
